# Generated by Django 5.2 on 2026-07-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("embedding", models.JSONField()),
                ("position", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="core.projectfile")),
            ],
            options={"ordering": ["position"]},
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(fields=("project_file", "position"), name="unique_file_chunk_position"),
        ),
    ]
